# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

#export LANG=zh_CN.utf8
export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot: +($debian_chroot)}\u@\h:\W\$ '

export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

export HADOOP_HOME="/Users/li.luo/dev/hadoop-current"
export KAFKA_HOME="/Users/li.luo/dev/kafka-current"
export PRESTO_HOME="/Users/li.luo/dev/presto-current"
export ZK_HOME="/Users/li.luo/dev/zookeeper-current"
export SPARK_HOME="/Users/li.luo/dev/spark-current"
export HIVE_HOME="/Users/li.luo/dev/hive-current"
#export BTRACE_HOME=~/disk2/soft/btrace-1.1.3
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export M2_HOME="/Users/li.luo/soft/packages/apache-maven-3.6.3"
export GRADLE_HOME="/Users/didi/soft/gradle-2.13"
export SCALA_HOME="/usr/local/opt/scala/idea"
export CLASSPATH=".:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
export ANT_HOME="/Users/didi/soft/apache-ant-1.9.7"
export BISON_HOME="/usr/local/Cellar/bison/3.0.4"
export PATH="$HIVE_HOME/bin:$HADOOP_HOME/bin:$SPARK_HOME/bin:$KAFKA_HOME/bin:$PRESTO_HOME/bin:$ZK_HOME/bin:$GRADLE_HOME/bin:$BISON_HOME/bin:$SCALA_HOME/bin:$BTRACE_HOME/bin:$M2_HOME/bin:$ANT_HOME/bin:$JAVA_HOME/bin:/usr/bin:/usr/local/bin:$PATH"

export MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=1024m"

alias la='ls -a'
alias vi='vim'
alias v='ls -l'
alias s='source ~/.bash_profile'
alias grep='grep --color' 
alias vb='vi ~/.bash_profile'
alias e='exit'

yjp_home="~/disk2/soft/yjp-12.0.5"
alias yjp="nohup ${yjp_home}/bin/yjp.sh 1>/tmp/yjp.log 2>&1 </dev/null &"

#alias unix2dos='todos' 
#alias dos2unix='fromdos'

alias hls='bin/hdfs dfs -ls '
alias hlsr='bin/hdfs dfs -lsr '
alias hrm='bin/hdfs dfs -rm '
alias hrmr='bin/hdfs dfs -rmr '
alias hget='bin/hdfs dfs -get '
alias hput='bin/hdfs dfs -put '
alias htouchz='bin/hdfs dfs -touchz '
alias hdu='bin/hdfs dfs -du '
alias hdus='bin/hdfs dfs -dus '
alias hcount='bin/hdfs dfs -count '
alias hmv='bin/hdfs dfs -mv '
alias hcat='bin/hdfs dfs -cat '
alias htext='bin/hdfs dfs -text '
alias hmkdir='bin/hdfs dfs -mkdir '

alias p='ibus-daemon -drx'

PATH=$PATH:$HOME/dev/soft/scala-2.10.3/bin:$HOME/.rvm/bin # Add RVM to PATH for scripting

#for mac shell color
#export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

#enables colorin the terminal bash shell export

export CLICOLOR=1
#sets up thecolor scheme for list export
LSCOLORS=gxfxcxdxbxegedabagacad

#sets up theprompt color (currently a green similar to linux terminal)
#export PS1='\u@\h:\w\$ '
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

#enables colorfor iTerm
#export TERM=linux


#github
alias gst='git status '
alias gbranch='git branch '
alias gcheckout='git checkout '
alias gpull='git pull '
alias gpush='git push '
alias gremote='git remote '
alias gadd='git add '
alias gcommit='git commit '
alias gfetch='git fetch '


#zhoushuanghui
alias tozshnn='ssh 120.55.74.90 -l root'


#alluxio
alias acleanbuild='mvn -T 2C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Pdeveloper -Dhadoop.version=2.6.0 '
alias abuild='mvn -T 2C install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Pdeveloper -Dhadoop.version=2.6.0 '
alias aeclipse='mvn clean -Pdeveloper -DskipTests eclipse:eclipse -DdownloadJavadocs=true -DdownloadSources=true '


# spark
alias scleanbuild="build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.6.0 -DskipTests -Phive -Phive-thriftserver -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip clean install "
alias sbuild="build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.6.0 -DskipTests -Phive -Phive-thriftserver -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip install "

# flink
alias fcleanbuild="mvn clean install -DskipTests -Dhadoop.version=2.6.1"
alias fbuild="mvn install -DskipTests -Dhadoop.version=2.6.1"

# shopee jump
alias jump0='ssh 103.115.76.108'
alias jump1='ssh 103.115.76.123'
alias ptunnel='cd ~/.ssh/ && ./shopee_tunnel.sh; cd -'
alias ops1='ssh ops1'
alias ops2='ssh ops2'

# cd apahce
alias cdpresto='cd /Users/li.luo/dev/presto-current'
alias cdkafka='cd /Users/li.luo/dev/kafka-current'
alias cdzk='cd /Users/li.luo/dev/zookeeper-current'
alias cdspark='cd /Users/li.luo/dev/spark-current'
alias cdh='cd /Users/li.luo/dev/hadoop-current'
alias cdhive='cd /Users/li.luo/dev/hive-current'
alias cddruid='cd /Users/li.luo/dev/druid-current'
